"""Add normalized session data and immutable source revision storage.

Revision ID: 0003_telemetry_pipeline
Revises: 0002_core_ingestion
"""

import sqlalchemy as sa
from alembic import op

revision = "0003_telemetry_pipeline"
down_revision = "0002_core_ingestion"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_driver_identities",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("driver_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "driver_number > 0",
            name=op.f("ck_session_driver_identities_positive_number"),
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_session_driver_identities_driver_id_drivers"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_driver_identities_session_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_driver_identities")),
        sa.UniqueConstraint(
            "provider", "session_id", "driver_id", name="uq_session_driver_domain"
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "driver_number", name="uq_session_driver_external"
        ),
    )
    op.create_index(
        op.f("ix_session_driver_identities_driver_id"),
        "session_driver_identities",
        ["driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_driver_identities_session_id"),
        "session_driver_identities",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "telemetry_source_records",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_telemetry_source_records_session_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_source_records")),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "kind",
            "source_key",
            "checksum",
            name="uq_telemetry_source_revision",
        ),
    )
    op.create_index(
        op.f("ix_telemetry_source_records_session_id"),
        "telemetry_source_records",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "interval_samples",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "gap_to_leader_seconds", sa.Numeric(precision=14, scale=6), nullable=True
        ),
        sa.Column("gap_to_leader_laps", sa.Integer(), nullable=True),
        sa.Column("interval_seconds", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("interval_laps", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gap_to_leader_laps >= 0 AND interval_laps >= 0",
            name=op.f("ck_interval_samples_nonnegative_lap_gaps"),
        ),
        sa.CheckConstraint(
            "gap_to_leader_seconds IS NULL OR gap_to_leader_laps IS NULL",
            name=op.f("ck_interval_samples_exclusive_gap_units"),
        ),
        sa.CheckConstraint(
            "interval_seconds IS NULL OR interval_laps IS NULL",
            name=op.f("ck_interval_samples_exclusive_interval_units"),
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_interval_samples_driver_id_drivers"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_interval_samples_session_id_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f("fk_interval_samples_source_record_id_telemetry_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interval_samples")),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "driver_id",
            "timestamp",
            name="uq_intervals_driver_time",
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "source_key", name="uq_interval_samples_source"
        ),
    )
    op.create_index(
        op.f("ix_interval_samples_driver_id"),
        "interval_samples",
        ["driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interval_samples_session_id"),
        "interval_samples",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interval_samples_timestamp"),
        "interval_samples",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "laps",
        sa.Column("lap_number", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("sector_1_seconds", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("sector_2_seconds", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("sector_3_seconds", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("is_pit_out_lap", sa.Boolean(), nullable=True),
        sa.Column("start_time_is_approximate", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_seconds >= 0 AND sector_1_seconds >= 0 AND "
            "sector_2_seconds >= 0 AND sector_3_seconds >= 0",
            name=op.f("ck_laps_nonnegative_durations"),
        ),
        sa.CheckConstraint("lap_number > 0", name=op.f("ck_laps_positive_lap")),
        sa.ForeignKeyConstraint(
            ["driver_id"], ["drivers.id"], name=op.f("fk_laps_driver_id_drivers")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_laps_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f("fk_laps_source_record_id_telemetry_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_laps")),
        sa.UniqueConstraint(
            "id", "session_id", "driver_id", "provider", name="uq_laps_sample_scope"
        ),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "driver_id",
            "lap_number",
            name="uq_laps_driver_number",
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "source_key", name="uq_laps_source"
        ),
    )
    op.create_index(op.f("ix_laps_driver_id"), "laps", ["driver_id"], unique=False)
    op.create_index(op.f("ix_laps_session_id"), "laps", ["session_id"], unique=False)
    op.create_table(
        "pit_stops",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lap_number", sa.Integer(), nullable=True),
        sa.Column(
            "lane_duration_seconds", sa.Numeric(precision=14, scale=6), nullable=True
        ),
        sa.Column(
            "stop_duration_seconds", sa.Numeric(precision=14, scale=6), nullable=True
        ),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lane_duration_seconds >= 0 AND stop_duration_seconds >= 0",
            name=op.f("ck_pit_stops_nonnegative_durations"),
        ),
        sa.CheckConstraint("lap_number > 0", name=op.f("ck_pit_stops_positive_lap")),
        sa.ForeignKeyConstraint(
            ["driver_id"], ["drivers.id"], name=op.f("fk_pit_stops_driver_id_drivers")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_pit_stops_session_id_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f("fk_pit_stops_source_record_id_telemetry_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pit_stops")),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "driver_id",
            "timestamp",
            name="uq_pits_driver_time",
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "source_key", name="uq_pit_stops_source"
        ),
    )
    op.create_index(
        op.f("ix_pit_stops_driver_id"), "pit_stops", ["driver_id"], unique=False
    )
    op.create_index(
        op.f("ix_pit_stops_session_id"), "pit_stops", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_pit_stops_timestamp"), "pit_stops", ["timestamp"], unique=False
    )
    op.create_table(
        "position_samples",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position > 0", name=op.f("ck_position_samples_positive_position")
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_position_samples_driver_id_drivers"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_position_samples_session_id_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f("fk_position_samples_source_record_id_telemetry_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_samples")),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "driver_id",
            "timestamp",
            name="uq_positions_driver_time",
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "source_key", name="uq_position_samples_source"
        ),
    )
    op.create_index(
        op.f("ix_position_samples_driver_id"),
        "position_samples",
        ["driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_position_samples_session_id"),
        "position_samples",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_position_samples_timestamp"),
        "position_samples",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "race_control_messages",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("flag", sa.String(length=100), nullable=True),
        sa.Column("scope", sa.String(length=100), nullable=True),
        sa.Column("lap_number", sa.Integer(), nullable=True),
        sa.Column("sector", sa.Integer(), nullable=True),
        sa.Column("qualifying_phase", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_race_control_messages_driver_id_drivers"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_race_control_messages_session_id_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f(
                "fk_race_control_messages_source_record_id_telemetry_source_records"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_control_messages")),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "source_key",
            name="uq_race_control_messages_source",
        ),
    )
    op.create_index(
        op.f("ix_race_control_messages_driver_id"),
        "race_control_messages",
        ["driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_race_control_messages_session_id"),
        "race_control_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_race_control_messages_timestamp"),
        "race_control_messages",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "stints",
        sa.Column("stint_number", sa.Integer(), nullable=False),
        sa.Column("lap_start", sa.Integer(), nullable=True),
        sa.Column("lap_end", sa.Integer(), nullable=True),
        sa.Column("compound", sa.String(length=30), nullable=True),
        sa.Column("tyre_age_at_start", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("lap_end >= lap_start", name=op.f("ck_stints_lap_order")),
        sa.CheckConstraint(
            "stint_number > 0 AND lap_start > 0",
            name=op.f("ck_stints_positive_numbers"),
        ),
        sa.CheckConstraint(
            "tyre_age_at_start >= 0", name=op.f("ck_stints_nonnegative_age")
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"], ["drivers.id"], name=op.f("fk_stints_driver_id_drivers")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_stints_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f("fk_stints_source_record_id_telemetry_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stints")),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "driver_id",
            "stint_number",
            name="uq_stints_driver_number",
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "source_key", name="uq_stints_source"
        ),
    )
    op.create_index(op.f("ix_stints_driver_id"), "stints", ["driver_id"], unique=False)
    op.create_index(
        op.f("ix_stints_session_id"), "stints", ["session_id"], unique=False
    )
    op.create_table(
        "weather_samples",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "air_temperature_c", sa.Numeric(precision=12, scale=6), nullable=True
        ),
        sa.Column(
            "track_temperature_c", sa.Numeric(precision=12, scale=6), nullable=True
        ),
        sa.Column("humidity_percent", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("pressure_mbar", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("rainfall", sa.Boolean(), nullable=True),
        sa.Column("wind_direction_degrees", sa.Integer(), nullable=True),
        sa.Column("wind_speed_mps", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "humidity_percent BETWEEN 0 AND 100",
            name=op.f("ck_weather_samples_humidity_range"),
        ),
        sa.CheckConstraint(
            "pressure_mbar >= 0 AND wind_speed_mps >= 0",
            name=op.f("ck_weather_samples_nonnegative_channels"),
        ),
        sa.CheckConstraint(
            "wind_direction_degrees BETWEEN 0 AND 359",
            name=op.f("ck_weather_samples_wind_range"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_weather_samples_session_id_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f("fk_weather_samples_source_record_id_telemetry_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_samples")),
        sa.UniqueConstraint(
            "provider", "session_id", "source_key", name="uq_weather_samples_source"
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "timestamp", name="uq_weather_time"
        ),
    )
    op.create_index(
        op.f("ix_weather_samples_session_id"),
        "weather_samples",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_samples_timestamp"),
        "weather_samples",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "telemetry_samples",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lap_id", sa.Uuid(), nullable=True),
        sa.Column("speed_kph", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("throttle_percent", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("brake_applied", sa.Boolean(), nullable=True),
        sa.Column("gear", sa.Integer(), nullable=True),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("drs_state", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "drs_state >= 0", name=op.f("ck_telemetry_samples_nonnegative_drs")
        ),
        sa.CheckConstraint(
            "gear BETWEEN 0 AND 8", name=op.f("ck_telemetry_samples_gear_range")
        ),
        sa.CheckConstraint(
            "speed_kph >= 0 AND rpm >= 0",
            name=op.f("ck_telemetry_samples_nonnegative_channels"),
        ),
        sa.CheckConstraint(
            "throttle_percent BETWEEN 0 AND 100",
            name=op.f("ck_telemetry_samples_throttle_range"),
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_telemetry_samples_driver_id_drivers"),
        ),
        sa.ForeignKeyConstraint(
            ["lap_id", "session_id", "driver_id", "provider"],
            ["laps.id", "laps.session_id", "laps.driver_id", "laps.provider"],
            name="fk_telemetry_lap_scope",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_telemetry_samples_session_id_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["telemetry_source_records.id"],
            name=op.f("fk_telemetry_samples_source_record_id_telemetry_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_samples")),
        sa.UniqueConstraint(
            "provider",
            "session_id",
            "driver_id",
            "timestamp",
            name="uq_telemetry_driver_time",
        ),
        sa.UniqueConstraint(
            "provider", "session_id", "source_key", name="uq_telemetry_samples_source"
        ),
    )
    op.create_index(
        op.f("ix_telemetry_samples_driver_id"),
        "telemetry_samples",
        ["driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_samples_lap_id"),
        "telemetry_samples",
        ["lap_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_samples_session_id"),
        "telemetry_samples",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_samples_timestamp"),
        "telemetry_samples",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telemetry_samples_timestamp"), table_name="telemetry_samples"
    )
    op.drop_index(
        op.f("ix_telemetry_samples_session_id"), table_name="telemetry_samples"
    )
    op.drop_index(op.f("ix_telemetry_samples_lap_id"), table_name="telemetry_samples")
    op.drop_index(
        op.f("ix_telemetry_samples_driver_id"), table_name="telemetry_samples"
    )
    op.drop_table("telemetry_samples")
    op.drop_index(op.f("ix_weather_samples_timestamp"), table_name="weather_samples")
    op.drop_index(op.f("ix_weather_samples_session_id"), table_name="weather_samples")
    op.drop_table("weather_samples")
    op.drop_index(op.f("ix_stints_session_id"), table_name="stints")
    op.drop_index(op.f("ix_stints_driver_id"), table_name="stints")
    op.drop_table("stints")
    op.drop_index(
        op.f("ix_race_control_messages_timestamp"), table_name="race_control_messages"
    )
    op.drop_index(
        op.f("ix_race_control_messages_session_id"), table_name="race_control_messages"
    )
    op.drop_index(
        op.f("ix_race_control_messages_driver_id"), table_name="race_control_messages"
    )
    op.drop_table("race_control_messages")
    op.drop_index(op.f("ix_position_samples_timestamp"), table_name="position_samples")
    op.drop_index(op.f("ix_position_samples_session_id"), table_name="position_samples")
    op.drop_index(op.f("ix_position_samples_driver_id"), table_name="position_samples")
    op.drop_table("position_samples")
    op.drop_index(op.f("ix_pit_stops_timestamp"), table_name="pit_stops")
    op.drop_index(op.f("ix_pit_stops_session_id"), table_name="pit_stops")
    op.drop_index(op.f("ix_pit_stops_driver_id"), table_name="pit_stops")
    op.drop_table("pit_stops")
    op.drop_index(op.f("ix_laps_session_id"), table_name="laps")
    op.drop_index(op.f("ix_laps_driver_id"), table_name="laps")
    op.drop_table("laps")
    op.drop_index(op.f("ix_interval_samples_timestamp"), table_name="interval_samples")
    op.drop_index(op.f("ix_interval_samples_session_id"), table_name="interval_samples")
    op.drop_index(op.f("ix_interval_samples_driver_id"), table_name="interval_samples")
    op.drop_table("interval_samples")
    op.drop_index(
        op.f("ix_telemetry_source_records_session_id"),
        table_name="telemetry_source_records",
    )
    op.drop_table("telemetry_source_records")
    op.drop_index(
        op.f("ix_session_driver_identities_session_id"),
        table_name="session_driver_identities",
    )
    op.drop_index(
        op.f("ix_session_driver_identities_driver_id"),
        table_name="session_driver_identities",
    )
    op.drop_table("session_driver_identities")
    # ### end Alembic commands ###
